### ISSUE TITLE
false-positive JSON size error from AWS

### ISSUE THREAD

**Issue by arjanvandervelde** [eugene-manuilov/cfpack#23]
Hi!

When validating templates as part of the 'build' task, the built template JSON gets _prettified_, increasing its size considerably. I noticed that for some of my larger templates it may grow by a factor of 2. The obvious fix would be to remove the two extra parameters from the call to `JSON.stringify()`, but that would leave us with pretty ugly error messages should validation fail for reasons other than size. Perhaps conditionally run it without these options for larger templates?

Thanks!

-- Arjan

see: https://github.com/eugene-manuilov/cfpack/blob/d1da970052d8cdd5f62fcd4e3bf3df50f2d14d74/src/tasks/Build.js#L133

**Comment by eugene-manuilov** [comment]
@arjanvandervelde I have just released a new version (`1.5.1`). It checks whether the prettified template is too big before sending it for verification and fallbacks to the non-prettified version if it exceeds 51200 bytes. Hope it helps to solve this issue. Can you try it on your end and let me know if it works for you?

**Comment by arjanvandervelde** [comment]
@eugene-manuilov thanks! I'll test the new version asap and get back to you.

**Comment by arjanvandervelde** [comment]
ok, it works as expected, https://github.com/eugene-manuilov/cfpack/commit/17b49fd0f824d90f103f89611dda67b3c651c1e6 fixed this issue. thanks!
